# coding: utf-8

"""
    Analysis Specification for Meta-analysis

    api to create a meta-analysis specification  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import neurosynth_compose_sdk
from neurosynth_compose_sdk.api.users_api import UsersApi  # noqa: E501
from neurosynth_compose_sdk.rest import ApiException


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = neurosynth_compose_sdk.api.users_api.UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_users_get(self):
        """Test case for users_get

        GET list of Users  # noqa: E501
        """
        pass

    def test_users_id_get(self):
        """Test case for users_id_get

        Get User Info by User ID  # noqa: E501
        """
        pass

    def test_users_id_put(self):
        """Test case for users_id_put

        Update User Information  # noqa: E501
        """
        pass

    def test_users_post(self):
        """Test case for users_post

        Create A New User  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
