"""
    Analysis Specification for Meta-analysis

    api to create a meta-analysis specification  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import neurosynth_compose_sdk
from neurosynth_compose_sdk.model.corrector import Corrector
from neurosynth_compose_sdk.model.estimator import Estimator
globals()['Corrector'] = Corrector
globals()['Estimator'] = Estimator
from neurosynth_compose_sdk.model.specification import Specification


class TestSpecification(unittest.TestCase):
    """Specification unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSpecification(self):
        """Test Specification"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Specification()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
