# coding: utf-8

"""
    Analysis Specification for Meta-analysis

    api to create a meta-analysis specification

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neurosynth_compose_sdk.api.tags_api import TagsApi


class TestTagsApi(unittest.TestCase):
    """TagsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TagsApi()

    def tearDown(self) -> None:
        pass

    def test_tags_get(self) -> None:
        """Test case for tags_get

        Get a list of Tags
        """
        pass

    def test_tags_id_get(self) -> None:
        """Test case for tags_id_get

        Get information about a Tag
        """
        pass

    def test_tags_post(self) -> None:
        """Test case for tags_post

        Create a new Tag
        """
        pass


if __name__ == '__main__':
    unittest.main()
