# coding: utf-8

"""
    Analysis Specification for Meta-analysis

    api to create a meta-analysis specification

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neurosynth_compose_sdk.models.project import Project

class TestProject(unittest.TestCase):
    """Project unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Project:
        """Test Project
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Project`
        """
        model = Project()
        if include_optional:
            return Project(
                provenance = None,
                meta_analyses = None,
                name = '',
                description = '',
                public = True,
                neurostore_study = neurosynth_compose_sdk.models.neurostore_study.neurostore-study(
                    neurostore_id = '', 
                    analyses = [
                        neurosynth_compose_sdk.models.neurostore_analysis.neurostore-analysis(
                            neurostore_id = '', 
                            exception = '', 
                            traceback = '', 
                            status = '', )
                        ], 
                    exception = '', 
                    traceback = '', 
                    status = '', ),
                neurostore_url = '',
                draft = True
            )
        else:
            return Project(
        )
        """

    def testProject(self):
        """Test Project"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
