"""
    Analysis Specification for Meta-analysis

    api to create a meta-analysis specification  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import neurosynth_compose_sdk
from neurosynth_compose_sdk.model.inline_response400 import InlineResponse400


class TestInlineResponse400(unittest.TestCase):
    """InlineResponse400 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse400(self):
        """Test InlineResponse400"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse400()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
