"""
    Analysis Specification for Meta-analysis

    api to create a meta-analysis specification  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import neurosynth_compose_sdk
from neurosynth_compose_sdk.api.annotations_api import AnnotationsApi  # noqa: E501
from neurosynth_compose_sdk.api_client import ApiClient

class TestAnnotationsApi(unittest.TestCase):
    """AnnotationsApi unit test stubs"""

    def setUp(self):
        self.api = AnnotationsApi(api_client=ApiClient())  # noqa: E501

    def tearDown(self):
        pass

    def test_annotations_get(self):
        """Test case for annotations_get

        GET a list of annotations  # noqa: E501
        """
        pass

    def test_annotations_id_get(self):
        """Test case for annotations_id_get

        GET information about an annotation  # noqa: E501
        """
        pass

    def test_annotations_id_put(self):
        """Test case for annotations_id_put

        Update an Annotation  # noqa: E501
        """
        pass

    def test_annotations_post(self):
        """Test case for annotations_post

        Create a new Annotation  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
