# coding: utf-8

"""
    Analysis Specification for Meta-analysis

    api to create a meta-analysis specification

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neurosynth_compose_sdk.api.put_api import PutApi


class TestPutApi(unittest.TestCase):
    """PutApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PutApi()

    def tearDown(self) -> None:
        pass

    def test_annotations_id_put(self) -> None:
        """Test case for annotations_id_put

        Update an Annotation
        """
        pass

    def test_meta_analyses_id_put(self) -> None:
        """Test case for meta_analyses_id_put

        Update a meta-analysis
        """
        pass

    def test_meta_analysis_results_id_put(self) -> None:
        """Test case for meta_analysis_results_id_put

        
        """
        pass

    def test_projects_id_put(self) -> None:
        """Test case for projects_id_put

        
        """
        pass

    def test_specifications_id_put(self) -> None:
        """Test case for specifications_id_put

        Update Meta-Analysis specification
        """
        pass

    def test_studysets_id_put(self) -> None:
        """Test case for studysets_id_put

        Update a Studyset
        """
        pass


if __name__ == '__main__':
    unittest.main()
