# coding: utf-8

"""
    Analysis Specification for Meta-analysis

    api to create a meta-analysis specification

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neurosynth_compose_sdk.models.annotation_update import AnnotationUpdate

class TestAnnotationUpdate(unittest.TestCase):
    """AnnotationUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AnnotationUpdate:
        """Test AnnotationUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AnnotationUpdate`
        """
        model = AnnotationUpdate()
        if include_optional:
            return AnnotationUpdate(
                neurostore_id = '',
                snapshot = neurosynth_compose_sdk.models.snapshot.snapshot(),
                studyset = '',
                neurostore_url = '',
                cached_studyset_id = ''
            )
        else:
            return AnnotationUpdate(
        )
        """

    def testAnnotationUpdate(self):
        """Test AnnotationUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
