# coding: utf-8

"""
    Analysis Specification for Meta-analysis

    api to create a meta-analysis specification  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by: https://openapi-generator.tech
"""

import unittest

import neurosynth_compose_sdk
from neurosynth_compose_sdk.model.specification_return import SpecificationReturn
from neurosynth_compose_sdk import configuration


class TestSpecificationReturn(unittest.TestCase):
    """SpecificationReturn unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
