# coding: utf-8

"""
    Analysis Specification for Meta-analysis

    api to create a meta-analysis specification  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by: https://openapi-generator.tech
"""

from neurosynth_compose_sdk.paths.annotations.get import AnnotationsGet
from neurosynth_compose_sdk.paths.annotations_id.get import AnnotationsIdGet
from neurosynth_compose_sdk.paths.annotations_id.put import AnnotationsIdPut
from neurosynth_compose_sdk.paths.annotations.post import AnnotationsPost


class AnnotationsApi(
    AnnotationsGet,
    AnnotationsIdGet,
    AnnotationsIdPut,
    AnnotationsPost,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
