# coding: utf-8

"""
    Analysis Specification for Meta-analysis

    api to create a meta-analysis specification  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by: https://openapi-generator.tech
"""

from neurosynth_compose_sdk.paths.annotations.get import AnnotationsGet
from neurosynth_compose_sdk.paths.annotations_id.get import AnnotationsIdGet
from neurosynth_compose_sdk.paths.annotations_id.put import AnnotationsIdPut
from neurosynth_compose_sdk.paths.annotations.post import AnnotationsPost
from neurosynth_compose_sdk.paths.meta_analyses.get import MetaAnalysesGet
from neurosynth_compose_sdk.paths.meta_analyses_id.get import MetaAnalysesIdGet
from neurosynth_compose_sdk.paths.meta_analyses_id.put import MetaAnalysesIdPut
from neurosynth_compose_sdk.paths.meta_analyses.post import MetaAnalysesPost
from neurosynth_compose_sdk.paths.meta_analysis_results.get import MetaAnalysisResultsGet
from neurosynth_compose_sdk.paths.meta_analysis_results_id.get import MetaAnalysisResultsIdGet
from neurosynth_compose_sdk.paths.meta_analysis_results_id.put import MetaAnalysisResultsIdPut
from neurosynth_compose_sdk.paths.meta_analysis_results.post import MetaAnalysisResultsPost
from neurosynth_compose_sdk.paths.neurovault_collections.get import NeurovaultCollectionsGet
from neurosynth_compose_sdk.paths.neurovault_collections_id.get import NeurovaultCollectionsIdGet
from neurosynth_compose_sdk.paths.neurovault_collections_id.put import NeurovaultCollectionsIdPut
from neurosynth_compose_sdk.paths.neurovault_collections.post import NeurovaultCollectionsPost
from neurosynth_compose_sdk.paths.neurovault_files.get import NeurovaultFilesGet
from neurosynth_compose_sdk.paths.neurovault_files_id.get import NeurovaultFilesIdGet
from neurosynth_compose_sdk.paths.neurovault_files_id.put import NeurovaultFilesIdPut
from neurosynth_compose_sdk.paths.neurovault_files.post import NeurovaultFilesPost
from neurosynth_compose_sdk.paths.projects.get import ProjectsGet
from neurosynth_compose_sdk.paths.projects_id.get import ProjectsIdGet
from neurosynth_compose_sdk.paths.projects_id.put import ProjectsIdPut
from neurosynth_compose_sdk.paths.projects.post import ProjectsPost
from neurosynth_compose_sdk.paths.specifications.get import SpecificationsGet
from neurosynth_compose_sdk.paths.specifications_id.get import SpecificationsIdGet
from neurosynth_compose_sdk.paths.specifications_id.put import SpecificationsIdPut
from neurosynth_compose_sdk.paths.specifications.post import SpecificationsPost
from neurosynth_compose_sdk.paths.studysets.get import StudysetsGet
from neurosynth_compose_sdk.paths.studysets_id.get import StudysetsIdGet
from neurosynth_compose_sdk.paths.studysets_id.put import StudysetsIdPut
from neurosynth_compose_sdk.paths.studysets.post import StudysetsPost


class ComposeApi(
    AnnotationsGet,
    AnnotationsIdGet,
    AnnotationsIdPut,
    AnnotationsPost,
    MetaAnalysesGet,
    MetaAnalysesIdGet,
    MetaAnalysesIdPut,
    MetaAnalysesPost,
    MetaAnalysisResultsGet,
    MetaAnalysisResultsIdGet,
    MetaAnalysisResultsIdPut,
    MetaAnalysisResultsPost,
    NeurovaultCollectionsGet,
    NeurovaultCollectionsIdGet,
    NeurovaultCollectionsIdPut,
    NeurovaultCollectionsPost,
    NeurovaultFilesGet,
    NeurovaultFilesIdGet,
    NeurovaultFilesIdPut,
    NeurovaultFilesPost,
    ProjectsGet,
    ProjectsIdGet,
    ProjectsIdPut,
    ProjectsPost,
    SpecificationsGet,
    SpecificationsIdGet,
    SpecificationsIdPut,
    SpecificationsPost,
    StudysetsGet,
    StudysetsIdGet,
    StudysetsIdPut,
    StudysetsPost,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
