# coding: utf-8

"""
    Analysis Specification for Meta-analysis

    api to create a meta-analysis specification  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by: https://openapi-generator.tech
"""

from neurosynth_compose_sdk.paths.meta_analyses.get import MetaAnalysesGet
from neurosynth_compose_sdk.paths.meta_analyses_id.get import MetaAnalysesIdGet
from neurosynth_compose_sdk.paths.meta_analyses_id.put import MetaAnalysesIdPut
from neurosynth_compose_sdk.paths.meta_analyses.post import MetaAnalysesPost
from neurosynth_compose_sdk.paths.meta_analysis_results.get import MetaAnalysisResultsGet
from neurosynth_compose_sdk.paths.meta_analysis_results_id.get import MetaAnalysisResultsIdGet
from neurosynth_compose_sdk.paths.meta_analysis_results_id.put import MetaAnalysisResultsIdPut
from neurosynth_compose_sdk.paths.meta_analysis_results.post import MetaAnalysisResultsPost


class MetaAnalysesApi(
    MetaAnalysesGet,
    MetaAnalysesIdGet,
    MetaAnalysesIdPut,
    MetaAnalysesPost,
    MetaAnalysisResultsGet,
    MetaAnalysisResultsIdGet,
    MetaAnalysisResultsIdPut,
    MetaAnalysisResultsPost,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
