# coding: utf-8

"""
    Analysis Specification for Meta-analysis

    api to create a meta-analysis specification  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by: https://openapi-generator.tech
"""

from neurosynth_compose_sdk.paths.specifications.get import SpecificationsGet
from neurosynth_compose_sdk.paths.specifications_id.get import SpecificationsIdGet
from neurosynth_compose_sdk.paths.specifications_id.put import SpecificationsIdPut
from neurosynth_compose_sdk.paths.specifications.post import SpecificationsPost


class SpecificationsApi(
    SpecificationsGet,
    SpecificationsIdGet,
    SpecificationsIdPut,
    SpecificationsPost,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
