# coding: utf-8

"""
    Analysis Specification for Meta-analysis

    api to create a meta-analysis specification  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by: https://openapi-generator.tech
"""

from neurosynth_compose_sdk.paths.studysets.get import StudysetsGet
from neurosynth_compose_sdk.paths.studysets_id.get import StudysetsIdGet
from neurosynth_compose_sdk.paths.studysets_id.put import StudysetsIdPut
from neurosynth_compose_sdk.paths.studysets.post import StudysetsPost


class StudysetsApi(
    StudysetsGet,
    StudysetsIdGet,
    StudysetsIdPut,
    StudysetsPost,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
