# coding: utf-8

"""
    Analysis Specification for Meta-analysis

    api to create a meta-analysis specification  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: jamesdkent21@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, StrictStr, conlist
from neurosynth_compose_sdk.models.neurostore_analysis import NeurostoreAnalysis

class NeurostoreStudy(BaseModel):
    """
    NeurostoreStudy
    """
    neurostore_id: Optional[StrictStr] = None
    analyses: Optional[conlist(NeurostoreAnalysis)] = None
    __properties = ["neurostore_id", "analyses"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> NeurostoreStudy:
        """Create an instance of NeurostoreStudy from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "neurostore_id",
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in analyses (list)
        _items = []
        if self.analyses:
            for _item in self.analyses:
                if _item:
                    _items.append(_item.to_dict())
            _dict['analyses'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> NeurostoreStudy:
        """Create an instance of NeurostoreStudy from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return NeurostoreStudy.parse_obj(obj)

        _obj = NeurostoreStudy.parse_obj({
            "neurostore_id": obj.get("neurostore_id"),
            "analyses": [NeurostoreAnalysis.from_dict(_item) for _item in obj.get("analyses")] if obj.get("analyses") is not None else None
        })
        return _obj

